#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>

#include <iostream>
#include<string>

using namespace std;

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
private:
	string function = "x^2 + y^2";
	int xMin = -10;
	int xMax = 10;
	int yMin = -10;
	int yMax = 10;
	int zMin = -10;
	int zMax = 10;
	bool inPerspective = true;
	bool inMap = false;

protected:
	// Handlers for MyFrame1 events;
	void showInfo(wxMouseEvent& event);
	void enterFunction(wxCommandEvent& event);
	void enterXMin(wxCommandEvent& event);
	void enterXMax(wxCommandEvent& event);
	void enterYMin(wxCommandEvent& event);
	void enterYMax(wxCommandEvent& event);
	void enterZMin(wxCommandEvent& event);
	void enterZMax(wxCommandEvent& event);
	void perspectiveClick(wxMouseEvent& event);
	void outlineClick(wxMouseEvent& event);
	void printClick(wxMouseEvent& event);
	void saveClick(wxMouseEvent& event);
	void generateClick(wxMouseEvent& event);

	string getFunction() const { return function; }
	bool checkFunction(string f) const;

	int getxMin() const { return xMin; }
	int getxMax() const { return xMax; }
	int getyMin() const { return yMin; }
	int getyMax() const { return yMax; }
	int getzMin() const { return zMin; }
	int getzMax() const { return zMax; }

	bool isPerspective() const { return inPerspective; }
	bool isMap() const { return inMap; }

public:
	/** Constructor */
	GUIMyFrame1(wxWindow* parent);
	//// end generated class members
	
};

#endif // __GUIMyFrame1__